### ISSUE TITLE
Free form line items are not displayed on Order View in admin

### ISSUE THREAD

**Issue by arthurpro** [oroinc/orocommerce#49]
The following datagrid configuration is incorrect.
The join is not taking into account free form line items, thus they are not displayed on the Order View in admin which is very bad!
https://github.com/orocommerce/orocommerce/blob/8b18064902193018c44136ec02e1072c0e139b3c/src/Oro/Bundle/OrderBundle/Resources/config/oro/datagrids.yml#L519-L550

I solved the problem via an event listener but I had to remove lines 547-550 in `Oro/Bundle/OrderBundle/Resources/config/oro/datagrids.yml` which is even worse.

My temporary solution:
```
    oro_order.event_listener.order_line_items_datagrid:
        class: 'Oro\Bundle\OrderBundle\EventListener\LineItemsDatagridListener'
        arguments:
            - @doctrine
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.orm_datasource.result.after.order-line-items-grid, method: onResultAfter }
```

```php
<?php

namespace Oro\Bundle\OrderBundle\EventListener;

use Symfony\Bridge\Doctrine\RegistryInterface;

use Oro\Bundle\ProductBundle\Entity\Repository\ProductRepository;

use Oro\Bundle\DataGridBundle\Datasource\ResultRecord;
use Oro\Bundle\DataGridBundle\Event\OrmResultAfter;

class LineItemsDatagridListener
{
    protected $registry;

    public function __construct(RegistryInterface $registry)
    {
        $this->registry = $registry;
    }

    /**
     * @param OrmResultAfter $event
     */
    public function onResultAfter(OrmResultAfter $event)
    {
	$repository = $this->getProductRepository();

        /** @var ResultRecord[] $records */
        $records = $event->getRecords();

	$skus = [];
        foreach ($records as $record) {
	    $product = $record->getValue('product');
	    if ($product) {
		$skus[] = $record->getValue('productSku');
	    }
        }

	if (empty($skus)) return;

	$products = $repository->getProductWithNamesBySku($skus);

	if (empty($products)) return;

	$skuName = [];
	foreach ($products as $product){
	    $names = $product->getNames();
	    if (!empty($names)){
                $skuName[$product->getSku()] = $names[0];
            }
	}

	if (empty($skuName)) return;

	foreach ($records as $record) {
	    $sku = $record->getValue('productSku');
	    if ($sku && isset($skuName[$sku])){
		$record->addData(['productName' => $skuName[$sku]]);
	    }
	}
    }

    /**
     * @return ProductRepository
     */
    protected function getProductRepository()
    {
        return $this->registry
            ->getManagerForClass('OroProductBundle:Product')
            ->getRepository('OroProductBundle:Product');
    }
}
```

I couldn't find a better solution quickly...
